### ISSUE TITLE
Can not set OnRefreshListener from within my activity

### ISSUE THREAD

**Issue by RafalManka** [dkmeteor/pull-to-refresh-sticky-list#1]
Hello,

Thanks for your awesome work first of all. 

I was just wondering if there is any particular reason why getWrappedList() returns upcasted ListView instead of PullToRefreshListView. Also why WrapperViewList is default instead of public? I changed that manually in the lib and I'm wondering if I will stumble upon any issues later on:-)

**Comment by dkmeteor** [comment]
Hmmm...... 
I just merged 
StickyListHeaders: https://github.com/emilsjolander/StickyListHeaders
and
Pull-to-refresh: https://github.com/johannilsson/android-pulltorefresh .

Because I need these two feature work together.
I didn't change any other things.

The WrapperViewList is default  in StickyListHeaders. 
See: https://github.com/emilsjolander/StickyListHeaders/blob/master/library/src/se/emilsjolander/stickylistheaders/WrapperViewList.java

and the same reson why getWrappedList() returns upcasted ListView. 

You can change them, I don't think it will cause issues.

**Comment by RafalManka** [comment]
ok, thanks it works. But I am experiencing one issue that i am struggling with. when I create adapter with no items and then asynchneously download them from api I get this "tap to refresh" message at the very top. how can I disable it without disabling pull-to-refresh functionality?

**Comment by RafalManka** [comment]
Ok, so I managed to resolve my issue, but I still do not understand why is it behaving like this. What does not work is this:

public onItemsRecievedFromAPI(List<ValueType> values){
   mAdapter.setValues(values);
   mAdapter.notifyDataSetChanged();
   stickyList.getWrappedList().onRefreshComplete();
}

this does work:

public onItemsRecievedFromAPI(List<ValueType> values){
   mAdapter.setValues(values);
   mAdapter.notifyDataSetChanged();
   new Handler().post(new Runnable() {

   @Override
   public void run() {
         stickyList.getWrappedList().onRefreshComplete();
      }
   });
}

**Comment by dkmeteor** [comment]
Did your `onItemsRecievedFromAPI(List values)` function  run in Main Thread (UI Thread)?

**Comment by RafalManka** [comment]
and again you are correct. my issues are resolved now, and I found on stackoverflow how to get rid of the "tap to refresh" functionality: http://stackoverflow.com/questions/17400248/tap-to-refresh-is-visible-all-the-time-and-gap-is-still-visible-on-list-view

Thanks man!
